---
- hosts: localhost
  gather_facts: false
  vars_files:
  - vars/vcenter.yml

  vars:
    local_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39343931373634663865343333333438643431363236323261386231376133306238646337343763
          6366373264393835653364303937613761626461633238350a353134393135383732393736363266
          66613238663234343963616164633565613632643139376163616232666335626236393735396564
          3532396233313139340a656632383939383864613931653465363464666539393139646530343036
          6634
  # Extra vars:
    # mod_name: Name to assign to VM. Set by Tower survey
    # mod_ip: IP to assign to VM. Set by Tower survey
    # mod_os: Template to clone from. Set by Tower survey

  tasks:
  - name: set DNS for windows
    set_fact:
         mod_dns: "10.0.0.11"
    when: mod_os == 'win-2016-base'
  - name: set DNS for linux
    set_fact:
         mod_dns: "10.0.0.10"
    when: mod_os == 'rhel-74-base'
  - name: clone guest
    vmware_guest:
      hostname: "{{ vc_host }}"
      username: "{{ vc_user }}"
      password: "{{ vc_pass }}"
      validate_certs: no
      datacenter: ONB
      cluster: NUC
      name: "{{ mod_name }}"
      template: "{{mod_os}}"
      networks:
      - name: VM Network
        ip: "{{ mod_ip }}"
        netmask: 255.255.255.0
        gateway: 10.0.0.1
        dns_servers: "{{ mod_dns }}"
      disk:
      - size_gb: 40
        datastore: Local01
      customization:
        name: "{{ mod_name}}.maxdepth.io"
        domain: maxdepth.io
        password: "{{ local_pass }}"
      wait_for_ip_address: yes
