---
- hosts: localhost
  vars_files:
  - vars/vcenter.yml

  vars:
    is_nix: false
    #mod_name:

  tasks:
  - name: Gather all registered virtual machines
    vmware_vm_facts:
      hostname: "{{ vc_host }}" 
      username: "{{ vc_user }}"
      password: "{{ vc_pass }}"
      validate_certs: false
    register: vmfacts

  - set_fact:
      is_nix: true  
    when: vmfacts.virtual_machines.{{mod_name}}.guest_fullname | regex_search('(Red Hat)')

  - fail:
      msg: "This is not a Red Hat system"
    when: is_nix != true

  - tower_group:
      name: unconfigured
      inventory: Lab
