---
- hosts: localhost
  vars_files:
  - vars/vcenter.yml

  vars:
    mod_vm: "dc"
    is_windows: false

  tasks:
  - name: Gather all registered virtual machines
    vmware_vm_facts:
      hostname: "{{ vc_host }}" 
      username: "{{ vc_user }}"
      password: "{{ vc_pass }}"
      validate_certs: false
    register: vmfacts

  - set_fact:
      is_windows: true  
    when: vmfacts.virtual_machines.{{mod_vm}}.guest_fullname | regex_search('(Windows)')

  - fail:
      msg: "This is not a Windows system"
    when: is_windows != true
